### ISSUE TITLE
New repack will be needed

### ISSUE THREAD

**Issue by rockstorm101** [HuayraLinux/pkg-arduino#2]
Hi, I'm afraid a new upstream repack will be needed because there are still many binary files that cannot be distributed. I'm working on the exact list but I open this issue to let you know.
```
Files-Excluded:
  *.jar
  *.class
  *.tgz
  *.so
  *.a
  *.cvsignore
  *.bz2
  build/macosx
  build/windows
  libraries/WiFi/extras/binary
  libraries/WiFi/extras/wifiHD/Release
  libraries/WiFi/extras/wifi_dnld/Release
  hardware/arduino/avr/firmwares/wifishield/binary
  hardware/arduino/avr/firmwares/wifishield/wifiHD/Release
  hardware/arduino/avr/firmwares/wifishield/wifi_dnld/Release
  app/src/processing/app/macosx/*
  arduino-core/src/processing/app/macosx/*
  arduino-core/src/processing/app/windows/*
  arduino-core/src/cc/arduino/os/windows/*
```

**Comment by iglosiggio** [comment]
Thanks for the issue! I saw the firmwares and blobs when i ran lintian yesterday.

I've still not deleted them because i thought they might be needed (and packaged in an arduino-firmware or similar).

After easter i will look into it ^^

**Comment by rockstorm101** [comment]
Just as a note, the above list works for me.

> I've still not deleted them because i thought they might be needed (and packaged in an arduino-firmware or similar).

I was going to ask you if they could be completely striped from the upstream tarball in case they are not needed to run the IDE. It seems to me they are some extra features, and the IDE could run perfectly without them.

For instance, the WiFi library could be packaged separately using this repository https://github.com/arduino-libraries/WiFi instead.

Even if an additional package (say arduino-firmware) was done, those binaries cannot be distributed as per the DFSG, only the source code of it.

> After easter i will look into it ^^

Great! Thanks, I might keep throwing stuff in here. Feel free to use or discard whatever you want.

**Comment by iglosiggio** [comment]
> Even if an additional package (say arduino-firmware) was done, those binaries cannot be distributed as per the DFSG, only the source code of it.

Thanks for the clarification!

**Comment by iglosiggio** [comment]
Hey, i'm currently wanting to fix this issue and i stumbled upon a problem.

Is the sourcecode of the bootloaders (and firmwares) available? Do we need to rebuild them?

The bootloaders are located in `hardware/arduino/avr/bootloaders`, the firmwares in `hardware/arduino/avr/firmwares`.

**Comment by iglosiggio** [comment]
I think that [this](https://github.com/HuayraLinux/pkg-arduino/blob/master/build/compile_everything.bash) script builds all the libraries (but not the firmwares), i'm unsure if all the binaries are really needed for arduino to work.

**Comment by iglosiggio** [comment]
I've made a new repack (removing even more macosx and windows files). Now lintian doesn't emit any errors on the source except for the files w/o licensing information (I will be working on this :smile:).

Feel free to reopen the issue if you think that i've made any mistakes!

**Comment by rockstorm101** [comment]
Good job, I've got a question here. The pristine tar branch has not been updated with either the second or the third repack, was this done on purpose?

**Comment by iglosiggio** [comment]
That was my fault, sorry! :sweat_smile:

**Comment by iglosiggio** [comment]
Pristine tar failed generating the last file :\
```
warning: pristine-gz cannot reproduce build of ../arduino_1.8.5+dfsg.3.orig.tar.gz; storing 64% size diff in delta (8314641 bytes)
(Please consider filing a bug report so the delta size can be improved.)
pristine-tar: committed arduino_1.8.5+dfsg.3.orig.tar.gz.delta to branch pristine-tar
```
